version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: ffi
    versions:
    - 1.14.2
