# Site settings
url: "https://newcastlesacredharp.co.uk"
title: "Newcastle Sacred Harp"
description: "Newcastle Sacred Harp sings Sacred Harp every Wednesday evening"
permalink: pretty
header_image: "/assets/images/newcastle_sacred_harp_logo.svg"
header_image_alt_text: "Newcastle Sacred Harp"
logo: "/assets/images/newcastle_sacred_harp_logo_social.png"

# Header nav
navigation_header:
  Home: /
  Annual All-Day: /all-day/
  Other North-East Singings: /other-north-east-singings/
  About Sacred Harp: /about-sacred-harp/

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

include:
  - _headers

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-seo-tag
